---
- name: Install haproxy package
  package:
    name:
      - haproxy
    state: latest
    update_cache: yes

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file_path }}"
  register: ha_config

- name: Start and enable haproxy service
  service:
    name: haproxy
    enabled: yes
    state: started
    daemon_reload: yes
  register: haproxy_start

- name: Restat haproxy service after config change
  service:
    name: haproxy
    state: restarted
  when: ha_config is changed

- name: Install keepalived latest packages
  package:
    name:
      - keepalived
    state: latest
    update_cache: yes

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file_path }}"
  register: ka_config

- name: Start and enable keepalived service
  service:
    name: keepalived
    enabled: yes
    state: started
    daemon_reload: yes

- name: Restart keepalived in case of config change
  service:
    name: keepalived
    state: restarted
  when: ka_config is changed
