---
- name: Install haproxy package
  become: true
  package:
    name: haproxy
    state: present
  register: check_if_present

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file_path }}"
  notify:
    - restart haproxy

- name: Install keepalived packages
  become: true
  package:
    name: keepalived
    state: present
  register: check_if_present

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_config_file_path }}"
  notify:
    - restart keepalived